### ISSUE TITLE
Isotope: Import data to SEAD Clearinghouse

### ISSUE THREAD

**Issue by roger-mahler** [humlab-sead/sead_clearinghouse_import#1]
Import the new isotope data to SEAD.

**Comment by roger-mahler** [comment]
Fixed problems:

[ x ] Added sheet alias `tbl_a_e_prep_method ` 
[ x ] Renamed sheet `tbl_analysis_e_prep_method `to `tbl_a_e_prep_method`

**Comment by roger-mahler** [comment]
```
WARNING tbl_isotopes has EXTRA DATA columns: projekt_id, isotope_type_id
WARNING Type clash: tbl_isotopes.measurment_value numeric<=>object
WARNING Type clash: tbl_isotope_types.alternativ_name character varying<=>float64
WARNING Type clash: tbl_relative_dates.notes text<=>float64
WARNING Type clash: tbl_relative_ages.abbreviation character varying<=>float64
WARNING Type clash: tbl_sites.national_site_identifier character varying<=>float64
WARNING Type clash: tbl_sites.site_location_accuracy character varying<=>float64
WARNING tbl_sample_groups has EXTRA DATA columns: Unnamed: 9, Unnamed: 8, Unnamed: 10
WARNING Type clash: tbl_physical_samples.date_sampled character varying<=>float64
WARNING tbl_datasets has EXTRA DATA columns: projekt_id
WARNING Type clash: tbl_dataset_masters.url text<=>float64
WARNING Type clash: tbl_dataset_submissions.date_submitted date<=>float64
WARNING tbl_contacts has EXTRA DATA columns: laste_name
WARNING Type clash: tbl_contacts.address_2 character varying<=>float64
WARNING Type clash: tbl_biblio.bugs_reference character varying<=>float64
WARNING Type clash: tbl_biblio.isbn character varying<=>float64
WARNING Type clash: tbl_biblio.year character varying<=>int64
WARNING tbl_isotope_measurments has EXTRA DATA columns: standard_id
WARNING Type clash: tbl_standards.standard_id integer<=>object
WARNING tbl_units has EXTRA DATA columns: unit_abrev
tbl_isotopes has no system id data column
ERROR tbl_isotopes has MISSING DATA columns: standard_id, isotope_id
CRITICAL ERROR Table tbl_isotopes has no column named "system_id"
CRITICAL ERROR Table tbl_isotopes has no PK named "None"
CRITICAL ERROR Table tbl_isotope_types has no PK named "None"
ERROR tbl_datasets has MISSING DATA columns: project_id
ERROR tbl_contacts has MISSING DATA columns: last_name
ERROR tbl_isotope_measurments has MISSING DATA columns: satndard_id
CRITICAL ERROR Table tbl_isotope_measurments has no PK named "None"
tbl_standards has no system id data column
CRITICAL ERROR Table tbl_standards has no column named "system_id"
CRITICAL ERROR Table tbl_standards has no PK named "None"
ERROR tbl_units has MISSING DATA columns: unit_abbrev
ABORTED CRITICAL ERROR isotop_data_latest 
Traceback (most recent call last):
  File "c:\Users\roma0050\Documents\Projects\SEAD\sead_clearinghouse_import\importer\process.py", line 64, in process
    option.xml_filename = parser.process_excel_to_xml(option, basename, timestamp)
  File "c:\Users\roma0050\Documents\Projects\SEAD\sead_clearinghouse_import\importer\parser.py", line 232, in process_excel_to_xml
    service.process(data, option.table_names)
  File "c:\Users\roma0050\Documents\Projects\SEAD\sead_clearinghouse_import\importer\parser.py", line 206, in process
    raise model.DataImportError("Process ABORTED since data does not conform to SPECIFICATION")
importer.model.exceptions.DataImportError: Process ABORTED since data does not conform to SPECIFICATION

```

**Comment by MGE4** [comment]
Tar en titt på problemen så skickar jag dig en ny fil när jag fixat de problemen, låter det okej?

**Comment by roger-mahler** [comment]
Note:
-  Import assumes that all FK references points to a local "system_id" in referenced table
-  All data tables must have a non null "system_id"
-  All data tables must have a PK column with a name equal to that specified in "Tables" meta-data PK-name field

**Comment by roger-mahler** [comment]
Errors and warnings from import of 20191017 data (sorry for the delay!)

```
WARNING Type clash: tbl_isotopes.measurment_value numeric<=>object
WARNING! Column tbl_isotopes.isotope_value_specifier_id: ends with "_id" but NOT marked as PK/FK
WARNING tbl_isotope_value_specifiers has EXTRA DATA columns: description, isotope_value_specifier_id, Name
CRITICAL ERROR Column tbl_isotopes.measurment_value has non-numeric values: Non detected
CRITICAL ERROR Table tbl_isotope_value_specifiers has no PK named "None"
ABORTED CRITICAL ERROR isotope_data_latest_20191017:
   Process ABORTED since submission does not conform to SPECIFICATION
```
These data tables must be added to SEAD as a change request i.e. we need to add the data to humlab-sead/sead_change_control/blob/master/general/deploy/20191012_DML_ISOTOPE_LOOKUP_DATA.sql.


```
CRITICAL ERROR tbl_isotope_types new values not allowed for lookup table.
CRITICAL ERROR tbl_data_types new values not allowed for lookup table.
CRITICAL ERROR tbl_sample_location_types new values not allowed for lookup table.
CRITICAL ERROR tbl_locations new values not allowed for lookup table.
CRITICAL ERROR tbl_dataset_masters new values not allowed for lookup table.
CRITICAL ERROR tbl_contacts new values not allowed for lookup table.
CRITICAL ERROR tbl_biblio new values not allowed for lookup table.
```

**Comment by roger-mahler** [comment]
### Table  tbl_isotope_value_specifiers:
 - Table  has wrong name in "Columns" in metadata. Ending "s" is missing.
 - Column "Name" in data file must also be renamed to "name",
```
WARNING tbl_isotope_value_specifiers has EXTRA DATA columns: description, isotope_value_specifier_id, Name
CRITICAL ERROR Table tbl_isotope_value_specifiers has no PK named "None"
```
### Table tbl_isotopes.measurment_value
 - Value "Non detected" not allowed (must be fixed in the same way as other non-numeric valeus)
```
CRITICAL ERROR Column tbl_isotopes.measurment_value has non-numeric values: Non detected
```

**Comment by MGE4** [comment]
I have updated the files and added them to the designated map, the problems should be fixed.
Looking at your code, i could not find any problems that stood out to me.

**Comment by MGE4** [comment]
Noticed a spelling error in "isotope_data_latest (FIX 6)", i fixed it and uploaded "isotope_data_latest (FIX 7)" with the corrections.

**Comment by roger-mahler** [comment]
Isotope data is imported. Remaining errors are logged in #18.
