### ISSUE TITLE
Dendro Build: Errors in import file

### ISSUE THREAD

**Issue by roger-mahler** [humlab-sead/sead_clearinghouse_import#15]
```
WARNING tbl_sample_group_coordinates has EXTRA DATA columns: sample_group_name
WARNING tbl_sample_group_description_type_sampling_contexts has EXTRA DATA columns: type name
WARNING! Duplicate check of tbl_site_references.system_id failed
CRITICAL ERROR tbl_sample_group_descriptions has NO DATA!
CRITICAL ERROR tbl_site_references has missing system id values
CRITICAL ERROR tbl_sites has missing system id values

ABORTED CRITICAL ERROR dendro_build_data_latest_20191213 
Process ABORTED since submission does not conform to SPECIFICATION
```

**Comment by roger-mahler** [comment]
CRITICAL ERROR tbl_sample_group_descriptions has NO DATA! => alias removed from meta
CRITICAL ERROR tbl_site_references has missing system id values => empty rows removed ????
CRITICAL ERROR tbl_sites has missing system id values => empty rows removed ????

**Comment by roger-mahler** [comment]
P[rocessing tbl_abundances...
Table tbl_abundances, id=1, process failed for column taxon_id
CRITICAL FAILURE: Table tbl_abundances 'DataFrame' object has no attribute 'system_id'
CRITICAL ERROR
Traceback (most recent call last):
  File "c:\Users\roma0050\Documents\Projects\SEAD\sead_clearinghouse_import\importer\xml_processor.py", line 136, in process_data
    fk_data_row = fk_data_table.loc[(fk_data_table.system_id == fk_system_id)]
  File "C:\Users\roma0050\.virtualenvs\sead_clearinghouse_import-dLHtNNd4\lib\site-packages\pandas\core\generic.py", line 5179, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'system_id'
ABORTED CRITICAL ERROR dendro_build_data_latest_20191213
Traceback (most recent call last):
  File "c:\Users\roma0050\Documents\Projects\SEAD\sead_clearinghouse_import\importer\process.py", line 92, in process
    option.xml_filename = self.process_excel_to_xml(option, basename, timestamp)
  File "c:\Users\roma0050\Documents\Projects\SEAD\sead_clearinghouse_import\importer\process.py", line 49, in process_excel_to_xml
    service.process(submission, option.table_names)
  File "c:\Users\roma0050\Documents\Projects\SEAD\sead_clearinghouse_import\importer\xml_processor.py", line 218, in process
    self.process_data(submission, data_tablenames)
  File "c:\Users\roma0050\Documents\Projects\SEAD\sead_clearinghouse_import\importer\xml_processor.py", line 136, in process_data
    fk_data_row = fk_data_table.loc[(fk_data_table.system_id == fk_system_id)]
  File "C:\Users\roma0050\.virtualenvs\sead_clearinghouse_import-dLHtNNd4\lib\site-packages\pandas\core\generic.py", line 5179, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'system_id'
(sead_clearinghouse_import) 
](url)

**Comment by roger-mahler** [comment]
Table `taxa_tree_master `is missing column `system_id`. I guess this is new records?

**Comment by roger-mahler** [comment]
Fixed
