### ISSUE TITLE
Isotope: Import errors

### ISSUE THREAD

**Issue by roger-mahler** [humlab-sead/sead_clearinghouse_import#17]
```
  --> Processing table ('tbl_isotope_measurements',)
ABORTED CRITICAL ERROR isotope_data_latest_20191213 
Traceback (most recent call last):
  File "c:\Users\roma0050\Documents\Projects\SEAD\sead_clearinghouse_import\importer\process.py", line 107, in process
    self.repository.explode_submission(option.submission_id, p_dry_run=False, p_add_missing_columns=False)
  File "c:\Users\roma0050\Documents\Projects\SEAD\sead_clearinghouse_import\importer\model\repository.py", line 79, in explode_submission
    cursor.callproc('clearing_house.fn_copy_extracted_values_to_entity_table', (submission_id, table_name_underscored))
psycopg2.errors.RaiseException: Table does not exist: tbl_isotope_measurements
CONTEXT:  PL/pgSQL function clearing_house.fn_copy_extracted_values_to_entity_table(integer,character varying,boolean) line 15 at RAISE

```

**Comment by roger-mahler** [comment]
Table does not exist: tbl_isotope_measurements

**Comment by roger-mahler** [comment]
Felstavning: measur**e**ments

**Comment by roger-mahler** [comment]
File "importer\process.py", line 107, in process
    self.repository.explode_submission(option.submission_id, p_dry_run=False, p_add_missing_columns=False)
  File "importer\model\repository.py", line 79, in explode_submission
    cursor.callproc('clearing_house.fn_copy_extracted_values_to_entity_table', (submission_id, table_name_underscored))
psycopg2.errors.UndefinedTable: relation "clearing_house.tbl_isotope_value_specifiers" does not exist
LINE 1: Delete From clearing_house.tbl_isotope_value_specifiers Wher...
                    ^
QUERY:  Delete From clearing_house.tbl_isotope_value_specifiers Where submission_id = 4;
CONTEXT:  PL/pgSQL function clearing_house.fn_copy_extracted_values_to_entity_table(integer,character varying,boolean) line 22 at EXECUTE

**Comment by roger-mahler** [comment]
Create Table clearing_house.tbl_isotope_value_specifiers (

        isotope_value_specifier_id integer not null,
        name character varying not null,
        description text not null,
        date_updated timestamp with time zone null,

        submission_id int not null,
        source_id int not null,
        local_db_id int not null,
        public_db_id int null,

        transport_type clearing_house.transport_type,
        transport_date timestamp with time zone,
        transport_id int,

        Constraint pk_tbl_isotope_value_specifiers Primary Key (submission_id, source_id, isotope_value_specifier_id)

	);
	
Create Index idx_tbl_isotope_value_specifiers_submission_id_public_id On clearing_house.tbl_isotope_value_specifiers (submission_id, public_db_id);

Select clearing_house.fn_generate_foreign_key_indexes();
Select clearing_house.fn_create_local_union_public_entity_views('clearing_house', 'clearing_house', FALSE, FALSE);

**Comment by roger-mahler** [comment]
# Kvarstående fel i Isotope data:

```
tbl_isotope_measurement refererar till method_id 23 som saknas i tbl_methods
	FIX: SÄTTS ATT REFERERA TILL tbl_methods.system_id = 1 (Isotope-ratio mass spectrometry)
	
tbl_sample_groups refererar till method_id 5 som saknas i tbl_methods
    FIX: SÄTTS ATT REFERERA TILL tbl_methods.system_id = 2 (Acid Extraction)
	
tbl_physical_samples	refererar till sample_type_id 	15 som saknas i tbl_sample_types	FIX: SÄTTS ATT REFERERA TILL tbl_sample_types.system_id = 1 (Ceramic part)

```
