### ISSUE TITLE
C14 import

### ISSUE THREAD

**Issue by roger-mahler** [humlab-sead/sead_clearinghouse_import#21]
Note that the import has been done using `metadata_latest_20191104.xlsx` (not `c14 metadata.xlsx`). It is preferable and more maintainable to have a common meta-data file for all imports. Please consolidate these files in case of differences.

There are two errors that prevents import from starting. 

```log
SHEET data_table_index: NOT FOUND
submission file has no data_table_index
NoneType: None
ABORTED CRITICAL ERROR c14_import_20200224 
```
Fix: Sheet `Index `renamed to `data_table_index`.

```log
ABORTED CRITICAL ERROR c14_import_20200224 
KeyError: 'tbl_physical_features'
```
Fix: Remove `tbl_physical_features` from `data_table_index`

**Comment by roger-mahler** [comment]
```log
ABORTED CRITICAL ERROR c14_import_20200224 
KeyError: 'tbl_physical_features'
```
Fix: Remove `tbl_physical_features` from `data_table_index`

**Comment by roger-mahler** [comment]
```log

PROCESS OF c14_import_20200224 STARTED
 ---> PARSING EXCEL EXCEL
Using alias tbl_a_e_prep_method for tbl_analysis_entity_prep_methods
Using alias tbl_s_g_description_types for tbl_sample_group_description_types
Using alias tbl_s_g_d_t_sampling_contexts for tbl_sample_group_description_type_sampling_contexts
Using alias tbl_s_g_sampling_contexts for tbl_sample_group_sampling_contexts
Using alias tbl_s_l_t_sampling_contexts for tbl_sample_location_type_sampling_contexts
SHEET tbl_abundance_elements: READ
SHEET tbl_abundance_ident_levels: NOT FOUND
SHEET tbl_abundance_modifications: NOT FOUND
SHEET tbl_abundances: NOT FOUND
SHEET tbl_activity_types: NOT FOUND
SHEET tbl_age_types: NOT FOUND
SHEET tbl_aggregate_datasets: NOT FOUND
SHEET tbl_aggregate_order_types: NOT FOUND
SHEET tbl_aggregate_sample_ages: NOT FOUND
SHEET tbl_aggregate_samples: NOT FOUND
SHEET tbl_alt_ref_types: READ
SHEET tbl_analysis_entities: READ
SHEET tbl_analysis_entity_ages: NOT FOUND
SHEET tbl_analysis_entity_dimensions: NOT FOUND
SHEET tbl_a_e_prep_method: NOT FOUND
SHEET tbl_biblio: READ
SHEET tbl_ceramics: NOT FOUND
SHEET tbl_ceramics_lookup: NOT FOUND
SHEET tbl_chron_controls: NOT FOUND
SHEET tbl_chron_control_types: NOT FOUND
SHEET tbl_chronologies: NOT FOUND
SHEET tbl_colours: NOT FOUND
SHEET tbl_contacts: READ
SHEET tbl_contact_types: READ
SHEET tbl_coordinate_method_dimensions: NOT FOUND
SHEET tbl_dataset_contacts: READ
SHEET tbl_dataset_masters: NOT FOUND
SHEET tbl_datasets: READ
SHEET tbl_dataset_submissions: READ
SHEET tbl_dataset_submission_types: READ
SHEET tbl_data_type_groups: NOT FOUND
SHEET tbl_data_types: NOT FOUND
SHEET tbl_dating_labs: READ
SHEET tbl_dating_material: READ
SHEET tbl_dating_uncertainty: NOT FOUND
SHEET tbl_dendro: NOT FOUND
SHEET tbl_dendro_date_notes: NOT FOUND
SHEET tbl_dendro_dates: NOT FOUND
SHEET tbl_dendro_lookup: NOT FOUND
SHEET tbl_dimensions: NOT FOUND
SHEET tbl_ecocode_definitions: NOT FOUND
SHEET tbl_ecocode_groups: NOT FOUND
SHEET tbl_ecocodes: NOT FOUND
SHEET tbl_ecocode_systems: NOT FOUND
SHEET tbl_error_uncertainties: NOT FOUND
SHEET tbl_features: READ
SHEET tbl_feature_types: READ
SHEET tbl_geochronology: READ
SHEET tbl_geochron_refs: NOT FOUND
SHEET tbl_horizons: NOT FOUND
SHEET tbl_identification_levels: NOT FOUND
SHEET tbl_image_types: NOT FOUND
SHEET tbl_imported_taxa_replacements: NOT FOUND
SHEET tbl_languages: NOT FOUND
SHEET tbl_lithology: NOT FOUND
SHEET tbl_locations: READ
SHEET tbl_location_types: READ
SHEET tbl_mcrdata_birmbeetledat: NOT FOUND
SHEET tbl_mcr_names: NOT FOUND
SHEET tbl_mcr_summary_data: NOT FOUND
SHEET tbl_measured_value_dimensions: NOT FOUND
SHEET tbl_measured_values: NOT FOUND
SHEET tbl_method_groups: READ
SHEET tbl_methods: READ
SHEET tbl_modification_types: NOT FOUND
SHEET tbl_physical_sample_features: READ
SHEET tbl_physical_samples: READ
SHEET tbl_projects: READ
SHEET tbl_project_stages: READ
SHEET tbl_project_types: READ
SHEET tbl_rdb: NOT FOUND
SHEET tbl_rdb_codes: NOT FOUND
SHEET tbl_rdb_systems: NOT FOUND
SHEET tbl_record_types: NOT FOUND
SHEET tbl_relative_age_refs: NOT FOUND
SHEET tbl_relative_ages: NOT FOUND
SHEET tbl_relative_age_types: NOT FOUND
SHEET tbl_relative_dates: NOT FOUND
SHEET tbl_sample_alt_refs: READ
SHEET tbl_sample_colours: NOT FOUND
SHEET tbl_sample_coordinates: NOT FOUND
SHEET tbl_sample_descriptions: NOT FOUND
SHEET tbl_sample_description_sample_group_contexts: NOT FOUND
SHEET tbl_sample_description_types: NOT FOUND
SHEET tbl_sample_dimensions: NOT FOUND
SHEET tbl_sample_group_coordinates: NOT FOUND
SHEET tbl_sample_group_descriptions: READ
SHEET tbl_s_g_description_types: READ
SHEET tbl_s_g_d_t_sampling_contexts: NOT FOUND
SHEET tbl_sample_group_dimensions: NOT FOUND
SHEET tbl_sample_group_images: NOT FOUND
SHEET tbl_sample_group_notes: NOT FOUND
SHEET tbl_sample_group_references: NOT FOUND
SHEET tbl_sample_groups: READ
SHEET tbl_s_g_sampling_contexts: NOT FOUND
SHEET tbl_sample_horizons: NOT FOUND
SHEET tbl_sample_images: NOT FOUND
SHEET tbl_sample_locations: NOT FOUND
SHEET tbl_sample_location_types: NOT FOUND
SHEET tbl_s_l_t_sampling_contexts: NOT FOUND
SHEET tbl_sample_notes: READ
SHEET tbl_sample_types: READ
SHEET tbl_season_or_qualifier: NOT FOUND
SHEET tbl_seasons: NOT FOUND
SHEET tbl_season_types: NOT FOUND
SHEET tbl_site_images: NOT FOUND
SHEET tbl_site_locations: READ
SHEET tbl_site_natgridrefs: NOT FOUND
SHEET tbl_site_other_records: NOT FOUND
SHEET tbl_site_preservation_status: NOT FOUND
SHEET tbl_site_references: READ
SHEET tbl_sites: READ
SHEET tbl_species_associations: NOT FOUND
SHEET tbl_species_association_types: NOT FOUND
SHEET tbl_taxa_common_names: NOT FOUND
SHEET tbl_taxa_images: NOT FOUND
SHEET tbl_taxa_measured_attributes: NOT FOUND
SHEET tbl_taxa_reference_specimens: NOT FOUND
SHEET tbl_taxa_seasonality: NOT FOUND
SHEET tbl_taxa_synonyms: NOT FOUND
SHEET tbl_taxa_tree_authors: NOT FOUND
SHEET tbl_taxa_tree_families: NOT FOUND
SHEET tbl_taxa_tree_genera: NOT FOUND
SHEET tbl_taxa_tree_master: READ
SHEET tbl_taxa_tree_orders: NOT FOUND
SHEET tbl_taxonomic_order: NOT FOUND
SHEET tbl_taxonomic_order_biblio: NOT FOUND
SHEET tbl_taxonomic_order_systems: NOT FOUND
SHEET tbl_taxonomy_notes: NOT FOUND
SHEET tbl_tephra_dates: NOT FOUND
SHEET tbl_tephra_refs: NOT FOUND
SHEET tbl_tephras: NOT FOUND
SHEET tbl_text_biology: NOT FOUND
SHEET tbl_text_distribution: NOT FOUND
SHEET tbl_text_identification_keys: NOT FOUND
SHEET tbl_units: READ
SHEET tbl_updates_log: NOT FOUND
SHEET tbl_years_types: NOT FOUND
SHEET tbl_isotopes: NOT FOUND
SHEET tbl_isotope_measurements: NOT FOUND
SHEET tbl_isotope_types: NOT FOUND
SHEET tbl_isotope_standards: NOT FOUND
SHEET tbl_isotope_value_specifiers: NOT FOUND
SHEET data_table_index: READ
WARNING Type clash: tbl_biblio.doi character varying<=>float64
WARNING Type clash: tbl_biblio.isbn character varying<=>float64
WARNING Type clash: tbl_biblio.year character varying<=>float64
WARNING tbl_contacts has EXTRA DATA columns: adress_2
WARNING Type clash: tbl_contacts.url text<=>float64
WARNING Type clash: tbl_dataset_submissions.date_submitted date<=>float64
WARNING tbl_datasets has EXTRA DATA columns: projekt_id
WARNING tbl_dating_labs has EXTRA DATA columns: contatc_id
WARNING! Column tbl_dating_labs.international_lab_id: ends with "_id" but NOT marked as PK/FK
WARNING! Column tbl_dating_labs.country_id: ends with "_id" but NOT marked as PK/FK
WARNING tbl_dating_material has EXTRA DATA columns: Unnamed: 8
WARNING Type clash: tbl_dating_material.description text<=>float64
WARNING Type clash: tbl_geochronology.notes text<=>float64
WARNING tbl_location_types has EXTRA DATA columns: loaction_type
WARNING tbl_method_groups has EXTRA DATA columns: record_type_id, record_type_name, record_type_description
WARNING Type clash: tbl_projects.project_abbrev_name character varying<=>float64
WARNING Type clash: tbl_projects.description text<=>float64
WARNING Type clash: tbl_sites.site_description text<=>float64
WARNING Type clash: tbl_sites.site_location_accuracy character varying<=>float64
WARNING tbl_units has EXTRA DATA columns: desription
CRITICAL ERROR tbl_analysis_entity_prep_methods has NO DATA!
CRITICAL ERROR tbl_biblio new values not allowed for lookup table.
CRITICAL ERROR tbl_chronologies has NO DATA!
ERROR tbl_contacts has MISSING DATA columns: address_2
ERROR tbl_datasets has MISSING DATA columns: project_id
ERROR tbl_dating_labs has MISSING DATA columns: contact_id
ERROR tbl_location_types has MISSING DATA columns: location_type
CRITICAL ERROR tbl_locations new values not allowed for lookup table.
ERROR tbl_method_groups has MISSING DATA columns: description, group_name, method_group_id
CRITICAL ERROR Table tbl_method_groups has no PK named "method_group_id"
CRITICAL ERROR tbl_sample_coordinates has NO DATA!
ERROR tbl_units has MISSING DATA columns: description
ABORTED CRITICAL ERROR c14_import_20200224 
Traceback (most recent call last):
  File "/home/roger/source/sead_clearinghouse_import/importer/process.py", line 92, in process
    option.xml_filename = self.process_excel_to_xml(option, basename, timestamp)
  File "/home/roger/source/sead_clearinghouse_import/importer/process.py", line 49, in process_excel_to_xml
    service.process(submission, option.table_names)
  File "/home/roger/source/sead_clearinghouse_import/importer/xml_processor.py", line 210, in process
    raise model.DataImportError("Process ABORTED since submission does not conform to SPECIFICATION")
importer.model.exceptions.DataImportError: Process ABORTED since submission does not conform to SPECIFICATION
```

**Comment by roger-mahler** [comment]
Note that only relevant log messages have been included. Some of the errors are probably caused by spelling errors:

```log
WARNING tbl_contacts has EXTRA DATA columns: adress_2
WARNING tbl_datasets has EXTRA DATA columns: projekt_id
WARNING tbl_dating_labs has EXTRA DATA columns: contatc_id
WARNING! Column tbl_dating_labs.international_lab_id: ends with "_id" but NOT marked as PK/FK
WARNING! Column tbl_dating_labs.country_id: ends with "_id" but NOT marked as PK/FK
WARNING tbl_location_types has EXTRA DATA columns: loaction_type
WARNING tbl_units has EXTRA DATA columns: desription
```

Some of these errors corresponds to missing columns:

```log
ERROR tbl_contacts has MISSING DATA columns: address_2
ERROR tbl_datasets has MISSING DATA columns: project_id
ERROR tbl_dating_labs has MISSING DATA columns: contact_id
ERROR tbl_location_types has MISSING DATA columns: location_type
ERROR tbl_method_groups has MISSING DATA columns: description, group_name, method_group_id
ERROR tbl_units has MISSING DATA columns: description
```

Some tables seems to have a reference, but are missing in the Excel:

```log
CRITICAL ERROR tbl_analysis_entity_prep_methods has NO DATA!
CRITICAL ERROR tbl_chronologies has NO DATA!
CRITICAL ERROR tbl_sample_coordinates has NO DATA!
```

Data for lookup tables must be added in advances as a separate change request:
```log
CRITICAL ERROR tbl_biblio new values not allowed for lookup table.
CRITICAL ERROR tbl_locations new values not allowed for lookup table.
```
This might be a meta-data error:
```log
CRITICAL ERROR Table tbl_method_groups has no PK named "method_group_id"
```

**Comment by MGE4** [comment]
metadata_latest_20191104.xlsx and c14 metadata.xlsx are the same, its just the name of the files that are different.

Ill have a look at the new errors and get back to you.

**Comment by MGE4** [comment]
"tbl_dating_labs.international_lab_id" is not a PK/FK and has to be renamed.

**Comment by MGE4** [comment]
"tbl_dating_labs.country_id" does not seam to be connected to anything?
